-- RUN THIS TO ENABLE CHAT
-- 1. Create Messages Table
create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    sender_id uuid references public.profiles(id) not null,
    recipient_id uuid references public.profiles(id),
    -- NULL = Public Channel, UUID = DM
    content text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- 2. Enable Realtime
alter publication supabase_realtime
add table public.messages;
-- 3. Enable RLS
alter table public.messages enable row level security;
-- 4. Policies
-- Everyone can read public messages (recipient_id is null)
create policy "Everyone can read public messages" on messages for
select using (recipient_id is null);
-- Users can read their own DMs
create policy "Users can read their own DMs" on messages for
select using (
        auth.uid() = sender_id
        or auth.uid() = recipient_id
    );
-- Users can send messages (to public or others)
create policy "Users can send messages" on messages for
insert with check (auth.uid() = sender_id);